apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p3djhvk6g-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:a86c9a47acfe886c9faf59ff12e6e87d428e3ad9@sha256:82e4e8b6f00f757ffe4fa1d12160f65b048d2f1e8eb17c0ae4cec34a9a5e8f95
          name: container-image
